### ISSUE TITLE
Compile Error: could not compile dependency :ssl_verify_fun, "mix compile" failed.

### ISSUE THREAD

**Issue by nelsonic** [dwyl/elixir-invoke-lambda-example#30]
```
src/ssl_verify_fun_cert_helpers.erl:64:1: Warning: function extract_dns_names_from_alt_names/2 is unused
%   64| extract_dns_names_from_alt_names([ExtValue | Rest], Acc) ->
%     | ^

could not compile dependency :ssl_verify_fun, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile ssl_verify_fun --force", update it with "mix deps.update ssl_verify_fun" or clean it with "mix deps.clean ssl_verify_fun"
```

<img width="1862" alt="image" src="https://github.com/dwyl/elixir-invoke-lambda-example/assets/194400/10449722-9fe4-4bc1-ad9f-50ade35f4ae3">

No idea what this is. but I infer that it's an issue with SSL Erlang library. 🤷‍♂️ 
Going to try updating the version of `Elixir` (+ `OTP`) on my laptop and see if that fixes it. 🤞

**Comment by nelsonic** [comment]
Updated to latest:

```
elixir -v

Erlang/OTP 26 [erts-14.2.1] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit] [dtrace]

Elixir 1.16.0 (compiled with Erlang/OTP 26)
```

Still getting the same error. 😢

**Comment by nelsonic** [comment]
Ran:
```sh
mix deps.upate --all
```

Updated quite a few things:

```
New:
  cowboy_telemetry 0.3.1
  expo 0.5.1
Unchanged:
  metrics 1.0.1
  mimerl 1.2.0
  phoenix_pubsub 1.1.2
  poison 3.1.0
Upgraded:
  certifi 2.5.1 => 2.12.0
  cowboy 2.7.0 => 2.10.0
  cowlib 2.8.0 => 2.12.1
  db_connection 2.2.1 => 2.6.0
  decimal 1.8.1 => 2.1.1 (major)
  ecto 3.3.2 => 3.11.1
  ecto_sql 3.3.3 => 3.11.1
  ex_aws 2.1.1 => 2.1.9
  ex_aws_lambda 2.0.1 => 2.1.0
  excoveralls 0.12.2 => 0.12.3
  file_system 0.2.8 => 0.2.10
  gettext 0.17.4 => 0.24.0 (minor)
  hackney 1.15.2 => 1.20.1
  idna 6.0.0 => 6.1.1
  jason 1.1.2 => 1.4.1
  mime 1.3.1 => 2.0.5 (major)
  parse_trans 3.3.0 => 3.4.1
  phoenix 1.4.13 => 1.4.18
  phoenix_ecto 4.1.0 => 4.4.3
  phoenix_html 2.14.0 => 2.14.3
  phoenix_live_reload 1.2.1 => 1.4.1
  plug 1.9.0 => 1.15.2
  plug_cowboy 2.1.2 => 2.6.1
  plug_crypto 1.1.0 => 2.0.0 (major)
  postgrex 0.15.3 => 0.17.4 (minor)
  ranch 1.7.1 => 1.8.0
  ssl_verify_fun 1.1.5 => 1.1.7
  telemetry 0.4.1 => 0.4.3
  unicode_util_compat 0.4.1 => 0.7.0 (minor)
* Updating phoenix (Hex package)
* Updating phoenix_ecto (Hex package)
* Updating ecto_sql (Hex package)
* Updating postgrex (Hex package)
* Updating phoenix_html (Hex package)
* Updating phoenix_live_reload (Hex package)
* Updating gettext (Hex package)
* Updating jason (Hex package)
* Updating plug_cowboy (Hex package)
* Updating ex_aws (Hex package)
* Updating ex_aws_lambda (Hex package)
* Updating hackney (Hex package)
* creating /Users/n/.mix/elixir/1-16/rebar3
* Updating excoveralls (Hex package)
* Updating certifi (Hex package)
* Updating idna (Hex package)
* Updating parse_trans (Hex package)
* Updating ssl_verify_fun (Hex package)
* Updating unicode_util_compat (Hex package)
* Updating cowboy (Hex package)
* Getting cowboy_telemetry (Hex package)
* Updating plug (Hex package)
* Updating mime (Hex package)
* Updating plug_crypto (Hex package)
* Updating telemetry (Hex package)
* Updating cowlib (Hex package)
* Updating ranch (Hex package)
* Getting expo (Hex package)
* Updating file_system (Hex package)
* Updating db_connection (Hex package)
* Updating decimal (Hex package)
* Updating ecto (Hex package)
```

**Comment by nelsonic** [comment]
Got the following error:

```
Generated app app

09:33:51.882 [info] Migrations already up
warning: :logger :level has been set to :warn in config files, please use :warning instead
  (logger 1.16.0) lib/logger/app.ex:102: Logger.App.default_level/0
  (logger 1.16.0) lib/logger/app.ex:35: Logger.App.start/2
  (kernel 9.2) application_master.erl:293: :application_master.start_it_old/4

** (Mix) Could not start application app: App.Application.start(:normal, []) returned an error: shutdown: failed to start child: AppWeb.Endpoint
    ** (EXIT) shutdown: failed to start child: Phoenix.PubSub.PG2
        ** (EXIT) shutdown: failed to start child: Phoenix.PubSub.PG2Server
            ** (EXIT) an exception was raised:
                ** (UndefinedFunctionError) function :pg2.create/1 is undefined or private
                    (kernel 9.2) :pg2.create({:phx, App.PubSub})
                    (phoenix_pubsub 1.1.2) lib/phoenix/pubsub/pg2_server.ex:43: Phoenix.PubSub.PG2Server.init/1
                    (stdlib 5.2) gen_server.erl:980: :gen_server.init_it/2
                    (stdlib 5.2) gen_server.erl:935: :gen_server.init_it/6
                    (stdlib 5.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
```

This is immensely frustrating. 😢

**Comment by nelsonic** [comment]
There is just _way_ too much to fix in this repo. The version of `Phoenix` is _ancient_:
https://github.com/dwyl/elixir-invoke-lambda-example/blob/0fc1219fda56823ff0ce2e96edabba851d4aee60/mix.exs#L39
If you try running https://diff.hex.pm it throws an error.

**Comment by nelsonic** [comment]
Thinking of just scrapping the whole thing and starting from scratch ... 🤷‍♂️

**Comment by nelsonic** [comment]
Relevant: https://github.com/elixir-lang/elixir/issues/12681#issuecomment-1598312912 🤞
